# Generated by Django 3.2.9 on 2022-02-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cltvspj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.CharField(blank=True, max_length=800)),
            ],
        ),
        migrations.AlterField(
            model_name='calculator',
            name='clt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='pj',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
